### ISSUE TITLE
undefined reference to `vaCreateBuffer'

### ISSUE THREAD

**Issue by cheeyeo** [vivienschilis/segmenter#1]
Hi

firstly great work on the segmenter and keeping it up to date

I was able to build it using ffmpeg10 using gcc

But after upgrading to ffmpeg11 the build process is broken with the following error:

/home/ubuntu/ffmpeg2012/build/lib/ffmpeg10/libavcodec.a(vaapi.o): In function `commit_slices':
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:97: undefined reference to`vaCreateBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:106: undefined reference to `vaCreateBuffer'
/home/ubuntu/ffmpeg2012/build/lib/ffmpeg10/libavcodec.a(vaapi.o): In function`alloc_buffer':
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:125: undefined reference to `vaCreateBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:127: undefined reference to`vaMapBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:125: undefined reference to `vaCreateBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:127: undefined reference to`vaMapBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:125: undefined reference to `vaCreateBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:127: undefined reference to`vaMapBuffer'
/home/ubuntu/ffmpeg2012/build/lib/ffmpeg10/libavcodec.a(vaapi.o): In function `destroy_buffers':
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:37: undefined reference to`vaDestroyBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:37: undefined reference to `vaDestroyBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:37: undefined reference to`vaDestroyBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:37: undefined reference to `vaDestroyBuffer'
/home/ubuntu/ffmpeg2012/build/lib/ffmpeg10/libavcodec.a(vaapi.o): In function`render_picture':
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:48: undefined reference to `vaUnmapBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:61: undefined reference to`vaBeginPicture'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:65: undefined reference to `vaRenderPicture'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:69: undefined reference to`vaRenderPicture'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:74: undefined reference to `vaEndPicture'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:52: undefined reference to`vaUnmapBuffer'
/home/ubuntu/ffmpeg2012/compile/ffmpeg-0.10.4/libavcodec/vaapi.c:57: undefined reference to `vaUnmapBuffer'

I have googled and it seems that it is an issue with the ffmpeg headers?

thanks for your help

**Comment by vivienschilis** [comment]
Oh cool.

Yeah didn't get time to update this makefile. I usually use https://github.com/vivienschilis/ffmpeg-head to compile ffmpeg.
Under OSX add -framework CoreFoundation -framework VideoDecodeAcceleration -framework QuartzCore inside the makefile ;)

**Comment by cheeyeo** [comment]
Hi Vivien

thanks for the reply and for updating the ffmpeg-head repo with regards to the segmenter

I found out subsequently that because I compiled ffmpeg from the git branch directly and did not disable vaapi

If you were to add '-lvda' to the compile flag it will resolve the problem.

I managed to compile it successfully with the '-lvda' flag on ubuntu 64 bit for both ffmpeg-git, ffmpeg-11 and ffmpeg-10

There is also a stackoverflow link to the issue above:

http://stackoverflow.com/questions/9803726/failed-to-compile-http-live-video-stream-segmenter-and-distributor

Hope this helps someone

**Comment by vivienschilis** [comment]
Thanks,

I updated it
